### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by computergeek125** [teslaworksumn/midi-lightshow#7]
Since we actually now have a document about software conventions, why not follow them?  Proposed change: rename to lightshow-midi

**Comment by bookdude13** [comment]
Good idea. To preserve the play on words, I propose lightshow-midishow. Too redundant?

**Comment by computergeek125** [comment]
lightshow-midilights perhaps?

**Comment by bookdude13** [comment]
I like it. Will change.
